[project]
name = "car-app-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "requests>=2.31.0",
]
